cat_dict = {'Економіка': 'economics',
            'Суспільство':'society',
            'Коронавірус': 'covid',
            'Інциденти': 'incidents',
            'Політика': 'politics',
            'Спорт': 'sport', 
            'Життя/lifestyle':'lifestyle',
            'Світ':'world',
            'Погода':'weather',
            'Технології':'technologies',
            'Шоу-бізнес':'showbiz',
            'Війна/Донбас':'war',
            'Карантин':'quarantine',
            'Закордонна політика':'affairs',
            'Інше':'other'}